### ISSUE TITLE
usage with akka?

### ISSUE THREAD

**Issue by bilal-fazlani** [sirthias/borer#1]
This is great stuff!

Is there an example of how this can be used directly with Akka?

**Comment by sirthias** [comment]
I'm afraid I don't fully understand your question.
_BORER_ will happy live together with Akka on your class path.
The [README section on Akka Support](https://github.com/sirthias/borer#akka-support) describes, how to get _BORER_ to work seamlessly with `akka.util.ByteString`.

What other integration are you looking for?

**Comment by bilal-fazlani** [comment]
My apologies for ambiguity. I was wondering if its possible to replace the default java serialiser in akka cluster with Borer.

I am asking this because I am not sure if we have static type information available at the time of deserialisation in akka cluster. 

Some example will help.

**Comment by sirthias** [comment]
One thing, that the README does not make clear right now (and maybe it should) is: _BORER_ does **not** use reflection or anything! At the decoding point it requires that you know what type to deserialize to! If you don't know, you need to build your own mechanism for transporting type information across the serialization gap.

So, I'm afraid _BORER_ (or CBOR) will not solve your problem with regard to static type information.
If I'm not mistaken, this independence of static type info is also the reason why the Akka team has actually choses to rely on the ugly and slow java serialization in the first place...
