### ISSUE TITLE
Parser allows \uXXXX escaping sequences out of JSON strings

### ISSUE THREAD

**Issue by plokhotnyuk** [sirthias/borer#11]
```
scala> io.bullet.borer.Json.decode(("1\u0030").getBytes).to[Int].value
res0: Int = 10

scala> io.bullet.borer.Json.decode(("[true\u002Cfalse]").getBytes).to[Array[Boolean]].value
res1: Array[Boolean] = Array(true, false)
```

**Comment by sirthias** [comment]
I couldn't reproduce this.
In the example snippet you posted the scala compiler (parser) would actually decode the character.
When I escape the backslash in order to move the decoding down to the _borer_ JSON parser everything works as expected.

**Comment by plokhotnyuk** [comment]
Ups, sorry for that.

**Comment by sirthias** [comment]
No problem at all!
Your help in improving _borer_ really is very much appreciated!
Thank you very much again, Andriy!
