### ISSUE TITLE
Question about how to get underlying Json binary representation

### ISSUE THREAD

**Issue by ndchandar** [sirthias/borer#112]
Hello,
I have a question. I am currently working on a project that's already using Circe and have to add Cbor support. Some of my ADTs have `Json` as member attributes. When i decode my cbor payload, I can either decode to a specific data type that's fully defined or to Dom Element (`Eg. borer.Json.decode(<someByteArray>).to[Element].value`). But what i need is to go from `Element` to Json binary representation and not an ADT. Due to certain restrictions i am unable to define ADTs that's fully defined and convert them using `to` combinator.  How can i do this ?

**Comment by sirthias** [comment]
Thank you for reaching out, @ndchandar!
I'm afraid I don't fully unterstand your question.
What exactly are you trying to do?
Can you show some (pseudo-)code that you would like to compile?

**Comment by ndchandar** [comment]
Thank you for your response. I think I found a solution to what I was looking but wanted your feedback

```
package com.mycompany.test

import java.nio.ByteBuffer
import java.nio.charset.StandardCharsets

import io.bullet.borer
import io.bullet.borer.Dom._
import io.bullet.borer.{Dom, Reader, Writer}
import io.circe
import io.circe.generic.semiauto.{deriveCodec => circeDeriveCodec}
import io.circe.jawn.JawnParser
import io.circe.syntax._

// For the application in question, `value` has many combinations and we don't have a fully defined ADT at this time
case class MyTestDeviceState(value: circe.Json, unit: Option[String] = None)

object MyTestDeviceState {
  val jawnParser = new JawnParser()

  // Circe Codec
  implicit val deviceStateCirceCodec: circe.Codec[MyTestDeviceState] = circeDeriveCodec

  // Borer Codecs
  implicit val deviceStateBorerEncoder: borer.Encoder[MyTestDeviceState] = (w: Writer, value: MyTestDeviceState) => {
    val bs      = value.asJson.noSpaces.getBytes(StandardCharsets.UTF_8)
    val element = borer.Json.decode(bs).to[Element].value
    w.write(element)
  }

  implicit val deviceStateDecoder: borer.Decoder[MyTestDeviceState] = (r: Reader) => {
    val element   = Dom.elementDecoder.read(r)
    val byteArray = borer.Json.encode(element).toByteArray

    jawnParser
      .parseByteBuffer(ByteBuffer.wrap(byteArray))
      .getOrElse(circe.Json.obj())
      .as[MyTestDeviceState]
      .getOrElse(MyTestDeviceState(circe.Json.obj()))
  }

  def main(args: Array[String]): Unit = {
    val js1 = circe.parser.parse(s""" {"f1": "hello world", "f2": 20 } """).getOrElse(circe.Json.obj())
    val ds1 = MyTestDeviceState(js1, Option("C"))
    // val ds1 = MyTestDeviceState(js1, None)

    val js2 = borer.Json.encode(ds1)
    println(s"js2: ${js2.toUtf8String}")

    val cb3 = borer.Cbor.encode(ds1).toByteArray
    val ds3 = borer.Cbor.decode(cb3).to[MyTestDeviceState].value
    println(s"ds3: $ds3")

    val ds4 = borer.Json.decode(js2.toByteArray).to[MyTestDeviceState].value
    println(s"ds4: $ds4")
  }
}
```

**Comment by sirthias** [comment]
Ok, I see.
So you would like your Circe codecs to determine the structure of the messages and then simply convert this exact message structure to and from CBOR.

Your solution should work fine although it's of course not very efficient to first do a completely JSON encoding/decoding round trip before (de)serializing to/from CBOR.

A better approach would be to use the circe codec only for the translation layer between your types and the circe JSON AST and then use borer to (de)serialize from and to that AST.
Now that I think of it this might actually be a nice addition to borer itself. I'll add a ticket for that.

One question out of interest:

If you need CBOR anyway, what keeps you from simply switching to borer-based serialization completely? Which features of circe are you using that borer doesn't provide?

**Comment by ndchandar** [comment]
Thank you. `circe-compat` sounds like a great idea. 

1. I have a large existing codebase that already uses Circe and it's time consuming to refactor them
2. Previously we were only supporting Json payloads. Our application now needs to support Cbor. 
3. Circe has nice api to traverse and manipulate json. We heavily use this.

**Comment by sirthias** [comment]
Ok. If you are using circe for traversing and manipulating JSON then circe is the right tool for the job. It sounds like the `circe-compat` would really be the way to go for you then.
I'll look into it next week.
