### ISSUE TITLE
Consider using more efficient SWAR techniques for parsing of numbers

### ISSUE THREAD

**Issue by plokhotnyuk** [sirthias/borer#114]
Usually, `IMUL` instruction [has latency 3 and throughput 1 (executed only on one execution port)](https://uops.info/html-instr/IMUL_R32_R32.html). It leads to port pressure and big latency when completion parsing of `Int` and  `Long` values.

Please, consider using of some [old trick for 8-digit values](http://govnokod.ru/13461#comment189156):
```
val res = (octa & 0x0F0F0F0F0F0F0F0FL) * 2561 >> 8
res = (x & 0x00FF00FF00FF00FFL) * 6553601 >> 16
res = (x & 0x0000FFFF0000FFFFL) * 42949672960001L >> 32
```

It can be even more suitable for parsing of `BigInt` and `BigDecimal` values, especially when combined with [efficient validation](https://github.com/lemire/Code-used-on-Daniel-Lemire-s-blog/blob/cf17899a4e433efc5b9318aa29f217c051085be3/2018/09/30/identifynumbers.c#L46), like:
```
((octa & (octa + 0x0606060606060606L)) & 0xF0F0F0F0F0F0F0F0L) == 0x3030303030303030L
```

And, for the last case you can pick ideas from [these routines](https://github.com/plokhotnyuk/jsoniter-scala/blob/1d516e390e88c4eb4fd3c7350cc28a9525553068/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L1714-L1827) how to make instantiation of `BigInt` and `BigDecimal` values faster.

Also, [here](https://travisdowns.github.io/blog/2019/06/11/speed-limits.html#portexecution-unit-limits) is a section about port/execution limits of the great article about performance "speed limits" on contemporary CPUs.

**Comment by sirthias** [comment]
Thank you for these pointers, @plokhotnyuk!
Awesome stuff!

**Comment by sirthias** [comment]
There were indeed quite a few more small optimization lurking between the lines.
This is the current state: https://github.com/sirthias/borer/blob/master/core/src/main/scala/io/bullet/borer/json/JsonParser.scala#L131-L207

Thank you again for pointing out the optimization potential!

**Comment by plokhotnyuk** [comment]
@sirthias Moreover, Intel encourages a new age to come! SIMD/SWAR branchless implementations are much more demanded after Jump Conditional Code (JCC) Erratum: https://github.com/oracle/graal/issues/1829

Also, I think that the current implementation still has room for improvement. As an example for small numbers with up to 8 digits a more efficient and fully branchless routine can be extracted: there is no need for multiplication on `value` argument when it is `0`, switch on `digitCount` with branching `0 >= value && value >= Long.MinValue / E` can be avoided and for `octa << N` parameters the `nlz` value can be reused.

**Comment by sirthias** [comment]
Yes, right.
I was shying away from pealing off the first iteration of the `parseDigit` tailrec so far but after giving it a proper attempt in the just committed https://github.com/sirthias/borer/commit/d84284c791408a5da6a2d0c6173a7e629f7d8a65 it turned out to be easier than I thought.

Thank you once again, @plokhotnyuk!!!

**Comment by plokhotnyuk** [comment]
@sirthias Great work, Mathias!

I'm observing up to 20% improvements of throughput in parsing of numbers on my Core i7 7700HQ with the latest microcode from Intel ;)

##1.2.0
```
[info] REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
[info] why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
[info] experiments, perform baseline and negative tests that provide experimental control, make sure
[info] the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
[info] Do not assume the numbers tell you what you want them to tell.
[info] Benchmark                            (size)   Mode  Cnt       Score       Error  Units
[info] ArrayOfBytesReading.borerJson           128  thrpt    5  425440.571 ±   638.293  ops/s
[info] ArrayOfCharsReading.borerJson           128  thrpt    5  352950.406 ±  1469.366  ops/s
[info] ArrayOfDoublesReading.borerJson         128  thrpt    5   88438.425 ±   621.345  ops/s
[info] ArrayOfFloatsReading.borerJson          128  thrpt    5   90810.651 ±   924.808  ops/s
[info] ArrayOfIntsReading.borerJson            128  thrpt    5  378461.337 ±   719.507  ops/s
[info] ArrayOfLongsReading.borerJson           128  thrpt    5  307601.267 ±  1882.517  ops/s
[info] ArrayOfShortsReading.borerJson          128  thrpt    5  432526.711 ±  2996.285  ops/s
```

##1.2.1-SNAPSHOT
```
[info] REMEMBER: The numbers below are just data. To gain reusable insights, you need to follow up on
[info] why the numbers are the way they are. Use profilers (see -prof, -lprof), design factorial
[info] experiments, perform baseline and negative tests that provide experimental control, make sure
[info] the benchmarking environment is safe on JVM/OS/HW level, ask for reviews from the domain experts.
[info] Do not assume the numbers tell you what you want them to tell.
[info] Benchmark                            (size)   Mode  Cnt       Score       Error  Units
[info] ArrayOfBytesReading.borerJson           128  thrpt    5  499535.631 ±  1868.084  ops/s
[info] ArrayOfCharsReading.borerJson           128  thrpt    5  342727.172 ±  1362.694  ops/s
[info] ArrayOfDoublesReading.borerJson         128  thrpt    5   90810.135 ±   395.221  ops/s
[info] ArrayOfFloatsReading.borerJson          128  thrpt    5   95667.485 ±   735.803  ops/s
[info] ArrayOfIntsReading.borerJson            128  thrpt    5  446073.293 ±  1729.767  ops/s
[info] ArrayOfLongsReading.borerJson           128  thrpt    5  282002.937 ±   596.110  ops/s
[info] ArrayOfShortsReading.borerJson          128  thrpt    5  478317.856 ±  3603.291  ops/s
```

Will you cut v1.2.1 for that?

**Comment by sirthias** [comment]
Cool.
Thanks for reporting these numbers.
Seeing that the improvements are indeed that significant I'll indeed publish a quick 1.2.1 release.
Thanks again!

**Comment by sirthias** [comment]
Ok, `v1.2.1` published and pushed...
