### ISSUE TITLE
Add `MapBasedCodecs.deriveNonUnaryXXX` macros

### ISSUE THREAD

**Issue by sirthias** [sirthias/borer#130]
as counterpart to `ArrayBasedCodecs.deriveUnaryXXX`.

**Comment by mushtaq** [comment]
From #36

> This comment is actually incorrect and mere copy-pasta from the `ArrayBasedCodecs`.

Oh. If I have Adt like:

```scala
sealed trait Base
case class A(a: Int)    extends Base
case class B(b: String) extends Base
... 10 such cases
implicit lazy val codec: Codec[Base] = MapBasedCodecs.deriveAllCodecs
```
This will encode `B("abc")` to `{"B":{"b":"abc"}}` and so on. 

To achieve unwrapped encodings (like `{"B":"abc"}` ) , I will have to add `ArrayBasedCodecs.deriveCodec` for each case explicitly. I just wish there was a better way to control this. 

Maybe `MapBasedCodecs.deriveAllCodecs` should default to unary codecs when available and `MapBasedCodecs.deriveAllNonUnaryCodecs` should do what it is currently doing?

**Comment by sirthias** [comment]
My current plan is this:

1. Make `ArrayBasedCodecs` and `MapBasedCodecs` completely symmetrical. Both get this full set of macros:

- `deriveEncoder`
- `deriveUnaryEncoder`
- `deriveNonUnaryEncoder`
- `deriveAllEncoders`
- `deriveDecoder`
- `deriveUnaryDecoder`
- `deriveNonUnaryDecoder`
- `deriveAllDecoders`
- `deriveCodec`
- `deriveUnaryCodec`
- `deriveNonUnaryCodec`
- `deriveAllCodecs`

2. Make `deriveAllXXX` always call the most specific sub-macros, i.e. `deriveUnaryXXX` for unary classes and `derviceNonUnaryXXX` for non-unary classes, but without the macro call being fully qualified!

This then allows you to freely configure what you want with imports.

For your use case it would likely be

```
import ArrayBasedCodec.deriveUnaryCodec
import MapBasedCodec.{deriveUnaryCodec => _, _}
```

Would that cover your use case?

**Comment by mushtaq** [comment]
Not sure I have fully understood what these 3 variations do:
```
deriveEncoder
deriveUnaryEncoder
deriveNonUnaryEncoder
```

Won't these 2 variations suffice?
```
deriveEncoder: derive unary encoder for unary class and non-unary encoder for non-unary class
deriveNonUnaryEncoder: alway derive non-unary encoder for all classes 
```

Then, "all" can have 2 analogous variations:
```
deriveAllEncoders: derive unary encoder for unary class and non-unary encoder for non-unary class
deriveAllNonUnaryEncoders: alway derive non-unary encoder for all classes 
```
 
Once these 4 variations are available for both `ArrayBasedCodecs` and `MapBasedCodecs` then I do not need to mix and match. For my use case I can simply use `MapBasedCodec.deriveAllEncoders`?

This is a bit confusing, so I may be missing the point.

**Comment by sirthias** [comment]
Thank you for your feedback, @mushtaq.
I think you're right. This has all become much too confusing.

So I decided to clean things up and remove all `deriveUnaryXXX` macros altogether.
As a replacement there is now `CompactMapBasedCodecs`, which is the same as `MapBasedCodecs`, but with unwrapped unary case classes.

The way I understand your use case this should be the most straight-forward and cleanest solution for you.

**Comment by sirthias** [comment]
Closed by https://github.com/sirthias/borer/commit/ea76070162f03bc16b63b78cc611b2332d7b8f6b.

**Comment by mushtaq** [comment]
@sirthias Wonderful. Thank you so much! Christmas is early for sure 😄 . 

I adopt this across the project as soon as it is out.
