### ISSUE TITLE
Is there a way to easily opt out of CBOR?

### ISSUE THREAD

**Issue by hseeberger** [sirthias/borer#148]
httpie by default uses `Accept: application/json, */*`. When importing the implicit marshallers provided by `io.bullet.borer.compat.akkaHttp._`, borer decides to use CBOR for strings. This can be dealt with by the below, but I wonder whether there is some other (easier) way to opt out of CBOR.

``` scala
  implicit def m[A: Encoder]: ToEntityMarshaller[A] =
    borerJsonMarshaller[A]()
```

**Comment by sirthias** [comment]
Yes, good idea, thank you for the suggestion!
https://github.com/sirthias/borer/commit/aac6d571dd1c6bd35aadb9c30645839ed75b3d10 switches the default to JSON and makes it easier to configure format preference on equal q-value.
