### ISSUE TITLE
Codec.forCaseClass fails for case classes with generics

### ISSUE THREAD

**Issue by Dollyg** [sirthias/borer#16]
`case class Address[T](x: T)`

`implicit def addressCodec[T: Encoder: Decoder]: Codec[Address[T]] = Codec.forCaseClass[Address[T]]`

The above code snippet fails with the exception:

type mismatch;
[error]  found   : Address[Nothing] => Option[Nothing]
[error]  required: Address[T] => Option[?]
[error]   implicit def addressCodec[T: Encoder: Decoder]: Codec[Address[T]] = Codec.forCaseClass[Address[T]]
[error]                                                                                                 ^
[error] one error found

**Comment by sirthias** [comment]
Thank you for reporting, @Dollyg !
This fix for this will be released with 0.9.0 very soon.
