### ISSUE TITLE
Writing a CBOR object as a byte array within another CBOR object

### ISSUE THREAD

**Issue by droark** [sirthias/borer#186]
Hi. I'm having some issues with Borer and have hit a brick wall. Basically, as the header says, I'm trying to take a CBOR-encoded object and write it as a byte array inside another CBOR-encoded object. The somewhat abstracted code is as follows. `foo` is the object that I want to write inside `bar`.

```
  implicit val cborEncoder = new Encoder[foo] {
    override def write(w: Writer, params: foo): Writer = {
      w.writeArrayHeader(3)

      w.writeArrayHeader(params.widgets.length)
      for(s <- params.widgets) {
        w.writeBytes(params.widgets.toBytes)
      }
      w.writeInt(params.widgetMakers)
      w.writeInt(params.widgetBuildTime)
    }
  }
```

(Note that the `foo` unit tests, which are not here, pass. I used cbor.me to verify the output.)

```
  implicit val cborEncoder = new Encoder[bar] {
    override def write(w: Writer, params: bar): Writer = {
      w.writeArrayHeader(2)

      w.writeTag(Tag.Other(2828))
      w.writeBytes(params.taggedBytes)

      w.writeBytes(Cbor.encode(params.fooObject).toByteArray)
    }
  }
```

If I comment out `w.writeBytes(Cbor.encode(params.fooObject).toByteArray)` from `bar` and set the array length to 1, I get correctly formatted CBOR. If I use that line, the resultant CBOR is broken. If I use `w.write(params.fooObject)` instead of `w.writeBytes(Cbor.encode(params.fooObject).toByteArray)`, the CBOR output is correct except for the fact that the `foo` object isn't written as a byte array; it's just written as a plain `foo` object.

Any thoughts on what I can do to fix this? I've looked high and low in the docs and source code and am hitting a wall.

Thank you!

**EDIT**: After going back over the actual on-the-wire bytes, I think I have some idea of what's happening. The code starts out writing the `bar` bytes, including the tag and such. So far so good. However, when `encode` is called on the `foo` object, it overwrites the `bar` data _on top of_ being correctly written as a byte array. Not sure if this is a bug in my code or the library. Either way, I can reproduce it every time. Any ideas on a workaround or, if this is a library bug, when it will be fixed? Thanks either way!

**EDIT 2**: It took way too long to figure out such a simple workaround for this problem. Just encode `foo` first, save the bytes, and then encode `bar` while writing the `foo` bytes as a byte array. I'd still like to know if there's a cleaner solution and/or if this is some sort of library issue, but as is, I can proceed. Thanks. I'll close this out.

**Comment by sirthias** [comment]
Thank you for reporting this, @droark!
From you description this looks like sth that I should definitely investigate properly.
So I'll reopen this ticket until everything is clear...

**Comment by sirthias** [comment]
Ok, just confirmed this to be a bug!
I'll get a fix out ASAP.
Thank you again for reporting this, Douglas!

**Comment by sirthias** [comment]
Note that, until the next release containing the fix is released, you can use `Cbor.encode(...).withConfig(Cbor.EncodingConfig(allowBufferCaching = false)).toByteArray`
on all _nested_ calls to work-around the problem.
On the outermost level buffer caching can remain enabled (but it doesn't hurt correctness if you simply disable buffer caching everywhere).
