### ISSUE TITLE
Encode enumerations defined as case objects with Type ID

### ISSUE THREAD

**Issue by ajaychandran** [sirthias/borer#189]
Is it possible to encode enumerations defined as case objects with just the Type ID?
Something along the lines of [deriveEnumerationReader](https://pureconfig.github.io/docs/overriding-behavior-for-sealed-families.html).

```scala

sealed trait Binary

object Binary {

  def values: List[Binary] = List(`0`, `1``)

  final case object `0` extends Binary
  final case object `1` extends Binary
}

// current encoding with ArrayBasedCodecs
// ["0",[]]
// [["0",[]],["1",[]]]

// preferred encoding
// ["0"] - (or "0" ?) for Binary.`0`
// [["0"], ["1"]] -  (or ["0", "1"] ?) for Binary.values

```

**Comment by sirthias** [comment]
If your whole ADT only consists of case objects I'd recommend [Enumeratum](https://github.com/lloydmeta/enumeratum), which gives you a few other benefits as well.

Then you can write sth like this:

```scala
abstract class IntEnumCompanion[T <: IntEnumEntry] extends IntEnum[T] {
  implicit val codec: Codec[T] =
    Codec[T](
      encoder = (w, x) => w.writeInt(x.value),
      decoder = r => withValue(r.readInt())
    )
}
```

and set up your companion object like this

```scala
object Binary extends IntEnumCompanion[Binary]
```

**Comment by ajaychandran** [comment]
Thanks for the info! Closing the ticket.
