### ISSUE TITLE
Unexpected default limit for JSON number mantissa

### ISSUE THREAD

**Issue by plokhotnyuk** [sirthias/borer#19]
By default Scala use `MathContext.DECIMAL128` with precision up to 34 decimal digits for `BigDecimal` instances, but in current version (0.8.1-SNAPSHOT) the limit is set to 32 and configs cannot be passed as parameters into `encode` and `decode` methods:

```
io.bullet.borer.Borer$Error$Overflow: JSON number mantissa longer than configured maximum of 32 digits [input position 1]
```

**Comment by sirthias** [comment]
Thank you once again for reporting, Andriy!
Much appreciated!
