### ISSUE TITLE
Cross publish to Scala.js 0.6.x

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#198]
The latest version (1.5.0) is published only for Scala.js 1.x. 

We tried to upgrade our libraries to Scala.js 1.x, but there are other blockers so we may have to stay on 0.6 for a while.

It will be great if 0.6 is supported a little longer.

**Comment by sirthias** [comment]
yes, ok, I'll see that I get a cross-built 1.5.0 release published...

**Comment by mushtaq** [comment]
Given that most ecosystem has now moved to scala.js 1.x, I would say this is low priority for me. See also this [discussion](https://github.com/scala-js/scala-js/issues/4045).

**Comment by sirthias** [comment]
Thank you, @mushtaq, I agree with you.
Seeing that my capacity isn't exactly abundant these day I'd be inclined to simply close this ticket.
