### ISSUE TITLE
Codec for ActorRef ?

### ISSUE THREAD

**Issue by shubhamJay** [sirthias/borer#208]
This is particularly needed while using borer for serialising actor messages which carry actor refs(which is the suggested way to pass around refs). 
Does it make sense for akka-compat module to provide a codec for ActorRef? 

An implementation for typed ActorRef could look something like this:

```
implicit def resolverFromSystem(system: ActorSystem[_]): ActorRefResolver = ActorRefResolver(system)

implicit def actorRefCodec[T](implicit resolver: ActorRefResolver): Codec[ActorRef[T]] =
  Codec.bimap[String, ActorRef[T]](
    resolver.toSerializationFormat,
    resolver.resolveActorRef
  ) 
```

For classic ActoRef, could look something like this:
``` 
def classicActorRefCodec[T](implicit extendedSystem: actor.ExtendedActorSystem): Codec[actor.ActorRef] = {
    Codec.bimap[String, actor.ActorRef](
      Serialization.serializedActorPath,
      extendedSystem.provider.resolveActorRef
    )
  }
```

**Comment by sirthias** [comment]
Yes, this looks like a good idea!
Thank you.

I'll include it in the next release...

**Comment by mushtaq** [comment]
As mentioned in [this issue](https://github.com/akka/akka/issues/27975#issuecomment-542097094), we do not need a dependency on `ActorSystem` for implementing `Codec[ActorRef[T]]`. One can write obtain it at runtime from a ThreadLocal like so:

```scala
implicit def actorRefCodec[T]: Codec[ActorRef[T]] = {
  val resolver = ActorRefResolver(Serialization.getCurrentTransportInformation().system.toTyped)

  Codec.bimap[String, ActorRef[T]](
    resolver.toSerializationFormat,
    resolver.resolveActorRef
  )
}
```

This will be good addition to the borer-akka module.

**Comment by sirthias** [comment]
Ah, right.
And I forgot to include it in the last release.
Sorry about that.

Will try again with the next one...
