### ISSUE TITLE
Ability to pass a configuration in encode/decode DSL wanted

### ISSUE THREAD

**Issue by plokhotnyuk** [sirthias/borer#21]
Please add a configuration parameter for the `Target` methods.

Implementation of it can use own default values, like here:
```
def encode[T: Encoder](value: T, config: EncodingConfig = EncodingConfig.default): EncodingSetup.JsonApi[T, EncodingConfig] =
    new EncodingSetup.Impl(value, Json, config, Receiver.nopWrapper, JsonRenderer)

def decode[T](input: T, config: DecodingConfig = DecodingConfig.default)(implicit w: Input.Wrapper[T]): DecodingSetup.Api[w.In, DecodingConfig] =
```

**Comment by sirthias** [comment]
Configuration is currently possible with

`Cbor.encode(value).withConfig(config)` rather than the `Cbor.encode(value, config = config)` that you propose.

To me the difference is negligible.
What's your use case?

**Comment by plokhotnyuk** [comment]
Main concern is about redundant allocations on chained calls.

**Comment by sirthias** [comment]
`withConfig` does not allocate anything, it merely sets a mutable var, so should be absolutely zero perf difference between the two versions

**Comment by plokhotnyuk** [comment]
Thanks for the explanation!

**Comment by sirthias** [comment]
@plokhotnyuk I've just released version 0.9.0 to sonatype and would be interested in how it performs in your benchmarks. How difficult is it for you to upgrade the borer version in your setup to 0.9.0 and kick off the benchmark generation?

**Comment by plokhotnyuk** [comment]
I have [upgraded benchmarks to the latest Borer](https://github.com/plokhotnyuk/jsoniter-scala/pull/286), and started [all of them on 5 JVMs](https://github.com/plokhotnyuk/jsoniter-scala/blob/64f07a5207bc5794e8c580ce7a779ab53b1eddcd/benchmark.sh) (ETA Monday evening).

Mathias, please, if possible, review Borer's part of benchmarks and [derivation of codecs](https://github.com/plokhotnyuk/jsoniter-scala/blob/c659de9f758508546535623a439864ab010855a5/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/BorerJsonEncodersDecoders.scala) for them and run them with different parameters, and kinds of input. 

Main value of `sbt-jmh` benchmarks are not only throughput scores, but also ability to see what is happening under hood using different profilers: `gc`,  `perfnorm`, `perfasm`, `jmh.extras.JFR`, `jmh.extras.Async`. Example of `sbt` commands for running them are [here](https://github.com/plokhotnyuk/jsoniter-scala#run-benchmarks).

**Comment by plokhotnyuk** [comment]
Mathias, I have published latest results of benchmarks with Borer 0.9.0 and others as usually [here](https://plokhotnyuk.github.io/jsoniter-scala/).

You can use a handy service of JMH Visualizer to see difference between previous run with Borer 0.8.0 on JDK 11 using [the following url](http://jmh.morethan.io/?sources=https://raw.githubusercontent.com/plokhotnyuk/jsoniter-scala/30ca7e738d3c2c21874289e8743a73054b5974d2/openjdk11.json,https://raw.githubusercontent.com/plokhotnyuk/jsoniter-scala/cf340c7b0023af34bc8ac7088c08ed13285f1dac/openjdk11.json) with links on Git history of results which are pushed to the `gh-pages` branch.
