### ISSUE TITLE
Provide a bimap for convenient Codec creation

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#25]
```scala
def bimap[From: Encoder: Decoder, To](to: From ⇒ To, from: To ⇒ From): Codec[To] = Codec(
    implicitly[Encoder[From]].contramap(from),
    implicitly[Decoder[From]].map(to)
)
```

**Comment by sirthias** [comment]
Great idea. Thank you!

**Comment by mushtaq** [comment]
@sirthias I think Codec.bimap should take encoder and decoder as implicit parameters to make this easy to use. 

If you agree, should I open another issue?

**Comment by sirthias** [comment]
Yes, this was clearly an oversight.
Just pushed https://github.com/sirthias/borer/commit/3262af0b852f44b1339c9dac32c226a093861075 to get this fixed.

Thank you for bringing this up!
