### ISSUE TITLE
Provide dedicated function for efficient encoding of unary case classes that does not compile for other case classes 

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#26]
Currently we do `import io.bullet.borer.derivation.MapBasedCodecs._` and then use `deriveCodec[T]` for all case classes except the unary case classes for which we use `Codec.forCaseClass[T]`.

This works, but is prone to error. We may end up using `Codec.forCaseClass[T]` for non-unary case classes, especially during the refactoring, resulting in mix of array-based and map-based encodings.

It will be good to have a dedicated function for the unary case classes which fails to compile if the case class is not unary.

**Comment by plokhotnyuk** [comment]
What is an unary case class? Is it like `AnyVal` extension with only one field?

**Comment by mushtaq** [comment]
I picked it from the [docs](https://github.com/sirthias/borer#case-classes). Case class with 1 field, need not extend AnyVal.

**Comment by plokhotnyuk** [comment]
@mushtaq Nice spot! It helped me [to add a benchmark for AnyVals](https://github.com/plokhotnyuk/jsoniter-scala/commit/7d9a38639405741633ced53071ecb6287bac392f).

I think too that separated and properly named function would be much safer and handy.

**Comment by sirthias** [comment]
Ok, I understand your use case.
I'll add a `forUnaryCaseClass` helper to `Encoder`, `Decoder` and `Codec` to make this easier...
Thank you for raising this!

**Comment by mushtaq** [comment]
@sirthias While using this library call I felt that `deriveCodecForUnaryCaseClass` is too verbose. Should we use `deriveCodecUnary` or `deriveUnaryCodec` instead?

**Comment by sirthias** [comment]
@mushtaq Yes, I agree. `deriveUnaryEncoder` / `deriveUnaryCodec` is much better.
Just pushed 895455f2b61743b4e7844547864b6f612fae9f13 with the fix.
Thank you again!
