### ISSUE TITLE
How to write codecs for mongodb json

### ISSUE THREAD

**Issue by bilal-fazlani** [sirthias/borer#271]
```
  trait MongoValue
  case class ObjectId(id: String) extends MongoValue
```

Mongo values are text but don't have double quotes

```
{
	"_id" : ObjectId("asdasasd124asdasd"),
```

I am trying to write a codec for `ObjectId`

So far, I have tried the following but it doesnt seems to work..

```
  object objEnc extends Encoder[ObjectId] {
    override def write(w: Writer, value: ObjectId): Writer = {
      w.writeBytes(s"ObjectId(${value.id})".getBytes)
    }
  }
```

I get this exception:

```
Exception in thread "main" io.bullet.borer.Borer$Error$Unsupported: The JSON renderer doesn't support byte strings (Output.ToByteArray index 0)
```

Is it possible to write codec of ObjectId ?

**Comment by bilal-fazlani** [comment]
using `w.writeString(s"ObjectId(${value.id})")` writes the value with double quotes

**Comment by bilal-fazlani** [comment]
I got the writer to work

```
  implicit object objEnc extends Encoder[ObjectId] {
    override def write(w: Writer, value: ObjectId): Writer = {
      w.output.writeStringAsAsciiBytes(s"""ObjectId("${value.id}")""")
      w
    }
  }
```

It feels like a hack.. but works. Please let me know if there is a clean way to do this.
Still no luck with reader though ..

**Comment by bilal-fazlani** [comment]
Implementing a decoder is difficult because it expects the value to be a valid json.. which not true in my case ..

**Comment by sirthias** [comment]
_borer_ implements a *JSON*-codec. What you are trying to parse isn't JSON, therefore you are somewhat out on your own there. To me it seems the best and most robust solution for your use case would be to pre-/post-process the input/output and turn it into actual JSON before feeding it to _borer_.
Would that work in your case?
It looks like a simple regex-based search & replace might suffice...

**Comment by bilal-fazlani** [comment]
You are right. I agree.
While search and replace will work, I explored more and found [BSON library](https://mongodb.github.io/mongo-scala-driver/1.2/bson/extended-json/). It seems like a the right tool for my current job.
