### ISSUE TITLE
Circe-compat not available for Scala.js

### ISSUE THREAD

**Issue by OndrejSpanel** [sirthias/borer#309]
It seems last version of circe-compat which is available for Scala.js is 1.4.0 for Scala.js 0.6.x (see https://mvnrepository.com/artifact/io.bullet/borer-compat-circe).

If the only reason is some straightforward porting needs to be done and nobody was interested so far, I might be able to contribute. Are there any other reasons, or some particular obstacles to expect?

**Comment by sirthias** [comment]
Hey Ondřej,
thanks for offering to chip in!
I don't see any issues with the port, but I suspect that it makes sense to first go for an overall upgrade to Scala.js 1.x.
If you don't want to attempt that I might be able to get to it myself, e.g. tomorrow...

**Comment by OndrejSpanel** [comment]
> to first go for an overall upgrade to Scala.js 1.x

That was exactly what I meant. I see no reason to continue 0.6,x support. I will see when I will be able to get to that (I doubt it will be today or tomorrow, though).

**Comment by sirthias** [comment]
Yeah, indeed. There is no reason to continue with 0.6.
I'll give it a try later on today...

**Comment by sirthias** [comment]
Actually, the reason for this is that I had to disable the build (and publishing) of the `compat-circe-js` module, because `circe-derivation_sjs1_2.1X` wasn't published yet at that point.

Now that this dependency is available the solution is to simply re-enable the build, which I'm doing now...
