### ISSUE TITLE
YAML input / output

### ISSUE THREAD

**Issue by OndrejSpanel** [sirthias/borer#310]
Besides of Json I would like to read and write YAML as well. I guess this should not be much difficult, if I understand it right all I need for that is implementing Input / Output interfaces. It is not my ambition to parse any possible YAML, only a simple subset of it which I can write as well.

Compared to JSON I think the difference is YAML parser needs to indentation aware both on input an output.

Do you see any particular obstacles to look for?

I see two possible ways how to implement this:

- a minimal YAML subset as a Scala code
- using SnakeyYAML parser

First way would be Scala.js compatible, second way would be able to provide much more complete YAML support, but would be limited to JVM. For my intended use I think both would work equally well. Which if the two, if any, would you prefer to consider publishing it as a `io.bullet` package?

**Comment by sirthias** [comment]
I don't think YAML reading/writing would be a good feature for _borer_.
YAML is an entirely different beast and has very little overlap with CBOR or JSON.
Why do you think _borer_ would be a good vehicle for your needs?

**Comment by OndrejSpanel** [comment]
I understand complete YAML is very different from JSON, however its subset can be used as a human friendly representation of JSON, which is what I currently do.

In my application I use serialization to achieve two things:

- file storage of structured data
- their network transfer

I currently use Circe, but it has two drawbacks for me:

- it is unable to handle binary formats for efficient network transfer
- it is not stream based, therefore writing large data to disk causes memory issues

I hope I will be able to use _borer_ instead of Circe. I think it meets all my needs, the only thing missing is YAML support.

If you are not interested in hosting such module, I can keep it either in my application, or publish it separately.

**Comment by sirthias** [comment]
I see.
So you essentially want to be able to read and write your alternative JSON syntax (say "YAML-JSON"), which supports exactly the same semantic features as JSON proper.
Then the only thing you'd need to write would be a `YamlJsonParser` and a `YamlJsonRenderer`, as an analog of the `JsonParser` and `JsonRenderer` that's already there.

The parsing and rendering layer is separated from everything else in a relatively clean way in _borer_, so this should in fact be possible without too many headaches, I think.

**Comment by OndrejSpanel** [comment]
As a temporary solution I use Circe to convert between Json and YAML and Borer is always facing JSON only. The data I want in YAML are quite small now, therefore this works sufficiently well for me.

If I ever decide to implement something more proper for Borer, I will open a new ticket.

**Comment by sirthias** [comment]
Ok, great. Thank you!
