### ISSUE TITLE
Configure derivation: different default value handling

### ISSUE THREAD

**Issue by OndrejSpanel** [sirthias/borer#311]
I have many case classes where I want the default values to be included (actually in my case `equals` cannot be implemented properly for them, as they are native JS types, but sometimes you want to include even members with proper comparison).

Currently borer always tries to skip default values in the output:

> During encoding a member whose value matches the default value is not written to the output at all.

Would it be possible to provide some configuration options (something like [circe-generic-extras](https://github.com/circe/circe-generic-extras)), which would give the user a way to change this?

Another option would be an opt-out annotation, similar to opt-in [transientDefault](http://avsystem.github.io/scala-commons/api/com/avsystem/commons/serialization/transientDefault.html) annotation used in GenCodecs.

Perhaps there is some way how to do this now with `DefaultValueAware`, but I am still struggling with combining this with derived encoders, and I would rather not define all my encoders manually.

**Comment by OndrejSpanel** [comment]
The only sensible workaround I have found so far is to avoid default parameters in constructors and to provide them in a companion object `apply` instead.

I was trying to use `DefaultValueAware` in a following way:

```
  implicit val colorRGBEncoder: Encoder[ColorRGB] = new Encoder.DefaultValueAware[ColorRGB] {
    def write(w: Writer, c: ColorRGB) = implicitly[Encoder[Seq[Double]]].write(w, Seq(c.r, c.g, c.b))
    override def withDefaultValue(defaultValue: ColorRGB): Encoder[ColorRGB] = this
  }

```

This does not seem to have any effect, the `ColorRGB` members of other objects still have their `equals` called at runtime.

**Comment by sirthias** [comment]
Thanks for the suggestion!

**Comment by OndrejSpanel** [comment]
Awesome, looking forward to that. I really did not expect to get this feature so soon.

I guess the way it is implemented I can decide which classes will use this feature and which not by bringing the config in their scope or not? That is really great.

Once it is published I will let you know how it works for me.

**Comment by OndrejSpanel** [comment]
Works like a charm. Thanks a lot for a super-quick implementation.

**Comment by sirthias** [comment]
Great! Thank you for the feedback!
