### ISSUE TITLE
Release for Scala 2.13.0

### ISSUE THREAD

**Issue by plokhotnyuk** [sirthias/borer#33]
`utest`, `scodec-bits`, and `akka-actors` are released for Scala 2.13.0 already

**Comment by plokhotnyuk** [comment]
`jsoniter-scala`, `spray-json`, `upickle` are also released with suffix 2.13
`circe` is on a way to the Maven Central repo
benchmarks for `jackson-module-scala` probably can work properly on its 2.13.0-RC3 artifact

**Comment by plokhotnyuk** [comment]
up

JFYK: I'm waiting for it without patience because I'm going to bump a default Scala version up for jsoniter-scala, run its benchmarks, and see [results](https://plokhotnyuk.github.io/jsoniter-scala/) with Scala 2.13.0

**Comment by sirthias** [comment]
yes, I'm on the release.
It's almost done... :)

**Comment by mushtaq** [comment]
> yes, I'm on the release.
> It's almost done... :)

Eagerly awaited :-)

**Comment by plokhotnyuk** [comment]
Borer v0.10.0 released for Scala 2.13.0
