### ISSUE TITLE
Fully-Automatic Derivation with nested sealed traits / case classes

### ISSUE THREAD

**Issue by ghostdogpr** [sirthias/borer#339]
If I change slightly the example from the docs and add a sealed trait for `Color`:
```scala
sealed trait Color
case class Blue() extends Color
case class Red()  extends Color

sealed trait Animal
case class Dog(age: Int, name: String)                      extends Animal
case class Cat(weight: Double, color: String, home: String) extends Animal
case class Fish(color: Color)                               extends Animal
case object Yeti                                            extends Animal
```

Then the following code
```scala
implicit val animalCodec = deriveAllCodecs[Animal]
```
Doesn't compile anymore (`Could not find implicit Encoder[Codecs.this.Color] for parameter `color` of case class Codecs.this.Fish`). 

Is there a way to get all the inner types derived automatically?

**Comment by ghostdogpr** [comment]
Same issue with a nested case class by the way:
```scala
sealed trait Animal
case class Dog(age: Int, name: String)                      extends Animal
case class Cat(weight: Double, color: String, home: String) extends Animal
case class Fish(color: NestedColor)                         extends Animal
case class NestedColor(value: String)
case object Yeti                                            extends Animal
```

`Could not find implicit Encoder[Codecs.this.NestedColor] for parameter `color` of case class Codecs.this.Fish`

**Comment by sirthias** [comment]
With `deriveAllCodecs[Animal]` you tell borer to generate codecs for all subtypes of `Animal`.
The error message tells you that you need a codec for `Color`.

So simply add a derivation for `Color` and put it before the one for `Animal`:

```scala
implicit val colorCodec = deriveAllCodecs[Color]
implicit val animalCodec = deriveAllCodecs[Animal]
```

**Comment by sirthias** [comment]
Similarly, in your second example, you need to a codec for `NestedColor` since there is none defined and the `deriveAllCodecs[Animal]` doesn't cover it since it's not a subtype of `Animal`.

**Comment by ghostdogpr** [comment]
So there is no way to get full auto derivation (like Circe for example) and generate codecs for all the nested types? I was investigating using Borer for an existing codebase with a large nested hierarchy and hoping there was a way to avoid adding hundred of calls to derive types individually 😀

**Comment by sirthias** [comment]
borer's derivation doesn't cross type hierarchies, no.
So you'll have to add one line per type hierarchy, not type.

This is intentional, since this way you have complete control over whether, where and how codecs are cached.
Will total magic derivation the question of how many different codecs are actually generated and whether and how they are cached is often very obscure. (See for example https://github.com/propensive/magnolia/issues/79).
Since this has often caused issues for us, especially in large codebases, so the current derivation approach appears as a good middle ground for us.

**Comment by ghostdogpr** [comment]
I see, thanks. Even though it's not great for production usage, it can be quite useful for quick prototyping. But I understand your point 👍
