### ISSUE TITLE
Json.encode fails on Array[Byte]

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#40]
**Test**

```scala
val bytes = "abc".getBytes()
Json.encode(bytes).toUtf8String
```

**Error**

```txt
io.bullet.borer.Borer$Error$Unsupported: The JSON renderer doesn't support byte strings (Output.ToByteArray index 0)
```

**Related**

All of the following works

```scala
Json.encode(bytes.head).toUtf8String
Cbor.encode(bytes.head).toByteArray
Cbor.encode(bytes).toByteArray
```

**Workaround**

```scala
implicit lazy val bytesEnc: Encoder[Array[Byte]] = targetSpecificEnc(
    cborEnc = Encoder.forByteArray,
    jsonEnc = Encoder.forArray[Byte]
  )

def targetSpecificEnc[T](cborEnc: Encoder[T], jsonEnc: Encoder[T]): Encoder[T] = { (writer, value) ⇒
  val enc = if (writer.target == Cbor) cborEnc else jsonEnc
  enc.write(writer, value)
}
```

We had to write an analogous target specific decoder for Array[Bytes]

**Comment by sirthias** [comment]
How would you expect raw bytes to be encoded in JSON?
Base64? Simple hex? As an array of JSON numbers?
IMHO there is no clear and valuable default strategy here, or is there?

**Comment by mushtaq** [comment]
@sirthias I agree that there is no natural default. But getting a runtime error is not nice.

For us, any default will work because we will rarely exercise this path when using the REST/Json. 

I would suggest we go ahead with `Encoder.forArray[Byte]` as the default because that is what most JSON libs do. 

Also, in this case encoder, we do not need to define the decoder, and the following works fine:
`Json.decode(Json.encode("abc".getBytes()).toByteArray).to[Array[Byte]].value`
