### ISSUE TITLE
Support for Akka event migration?

### ISSUE THREAD

**Issue by PawelLipski** [sirthias/borer#400]
Akka Persistence provides docs on how to migrate events when using Jackson-based serializer: https://doc.akka.io/docs/akka/current/serialization-jackson.html#schema-evolution

or a protobuf-based one: https://doc.akka.io/docs/akka/current/persistence-schema-evolution.html

[akka-kryo](https://github.com/altoo-ag/akka-kryo-serialization) docs, in turn, explicitly state that:

_Note that this serializer is mainly intended to be used for akka-remoting and not for (long term) persisted data. The underlying kryo serializer does not guarantee compatibility between major versions._

How is Borer positioned between these two extremes? 🤔 
Would it be possible to add migration support to Borer?

**Comment by sirthias** [comment]
Hi Pawel,
I'm sorry for the late reply, I only saw this ticket just now.

Schema evolution with _borer _can be implemented in a way that's very similar to what the Akka docs say about Jackson.
If you use the `MapBasedCodecs` unused members are simply skipped during decoding and members with default values are properly initialized if the respective member is not present.

_borer_ itself has no concept of codec "versions" itself, but it's easy to add the level of your application in the form most appropriate for your use case, e.g. via some `Envelope[T]` type holding the encoding version as an `Int`, for example.

Then, in your deserialization layer you could use _borer's_ support for [transcoding](https://sirthias.github.io/borer/borer-core/transcoding.html) whenever a "migration" is required. The basic idea is to not decode directly into your target type but first into sth like _borer's_ [DOM representation](https://sirthias.github.io/borer/borer-core/DOM.html), which you freely manipulate, and then afterwards transcode from the patched DOM into your target type.

This should give you full flexibility in implementing schema evolution exactly as you need it...
