### ISSUE TITLE
Helpers for target specific codecs

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#41]
Often we want slightly different codecs for Json vs Cbor. We have defined the helpers like these:

```scala
def targetSpecificEnc[T](cborEnc: Encoder[T], jsonEnc: Encoder[T]): Encoder[T] = { (writer, value) ⇒
  val enc = if (writer.target == Cbor) cborEnc else jsonEnc
  enc.write(writer, value)
}

def targetSpecificDec[T](cborDec: Decoder[T], jsonDec: Decoder[T]): Decoder[T] = { reader ⇒
  val dec = if (reader.target == Cbor) cborDec else jsonDec
  dec.read(reader)
}
```

Which we use to define Instant codecs like these:

```scala
implicit lazy val instantEnc: Encoder[Instant] = CborHelpers.targetSpecificEnc(
  cborEnc = Encoder.forTuple2[Long, Long].contramap(x => (x.getEpochSecond, x.getNano)),
  jsonEnc = Encoder.forString.contramap(_.toString)
)

implicit lazy val instantDec: Decoder[Instant] = CborHelpers.targetSpecificDec(
  cborDec = Decoder.forTuple2[Long, Long].map(t => Instant.ofEpochSecond(t._1, t._2)),
  jsonDec = Decoder.forString.map(Instant.parse)
)
```

I hope this is the right way to go about doing this. If so, it will be good to have these helpers in the library.

**Comment by plokhotnyuk** [comment]
@mushtaq just for curiosity created a benchmark for your codecs, which have to serialize or parse an array of `java.time.Instant` values, so you can follow by a link above to see results

DECLAIMER: Please, do not do any business decisions. Borer constantly improving and I hope it will end up in line with the best Scala parsers for binary and text representation.

**Comment by mushtaq** [comment]
@plokhotnyuk thanks 👍 

I am aware of jsoniter. What borer gives is the cross-compilation to Scala.js. Also, could see any docs on how to transform existing codecs to create the new ones in jsoniter, which is a very common use-case for us.

**Comment by plokhotnyuk** [comment]
@mushtaq you are welcome! 

Yes, you are right, the lib and docs could be better. For your case it would be code like this:

```
object JsonValueCodec {
  def apply[@scala.specialized A, @scala.specialized B](z: () => B)(f: A => B, g: B => A)
                                                       (implicit c: JsonValueCodec[A]): JsonValueCodec[B] = 
    new JsonValueCodec[B] {
      def decodeValue(in: JsonReader, default: B): B = f(c.decodeValue(in, g(default)))
  
      def encodeValue(x: B, out: JsonWriter): Unit = c.encodeValue(g(x), out)
  
      def nullValue: B = z()
    }
}
```

Also, I'm not going to rush anybody to use jsoniter-scala... Moreover, I would like that best of its algorithms and approaches landed in better places for wider usage. But from the other hand do not hesitate to ask questions in [issues](https://github.com/plokhotnyuk/jsoniter-scala/issues) or [chat](https://gitter.im/plokhotnyuk/jsoniter-scala).

**Comment by sirthias** [comment]
Thank you, @mushtaq, this is a nice idea!
