### ISSUE TITLE
CBOR tag `EpochDateTime` cannot be represented in the circe JSON AST` when using BigDecimal

### ISSUE THREAD

**Issue by etspaceman** [sirthias/borer#418]
Hello - 

I'm attempting to update my project to use a `BigDecimal` format for `java.time.Instant`. However, Borer throws an error when using this.

Check out my PR here for more information on the changes that I'm attempting to implement:

https://github.com/etspaceman/kinesis-mock/pull/76

**Comment by sirthias** [comment]
Thank you for reaching out!
However, you neither show the code you are trying to run nor the error that _borer_ is throwing.
So my options in helping you are extremely limited.
Please provide more details on what you are trying to achieve, how you are doing it and the problem you are facing.

**Comment by etspaceman** [comment]
Sure.

So I am using the Circe compat to convert between Circe Encoder/Decoder values and the Borer offerings:

You can see the new instances that I am attempting to introduce here:

https://github.com/etspaceman/kinesis-mock/blob/fixTimestampCirce/src/main/scala/kinesis/mock/instances/circeBigDecimalInstant.scala

And you can see where I leverage the instances here:

https://github.com/etspaceman/kinesis-mock/blob/fixTimestampCirce/src/main/scala/kinesis/mock/instances/http4s.scala#L9

https://github.com/etspaceman/kinesis-mock/blob/fixTimestampCirce/src/main/scala/kinesis/mock/instances/http4s.scala#L33

https://github.com/etspaceman/kinesis-mock/blob/fixTimestampCirce/src/main/scala/kinesis/mock/instances/http4s.scala#L63

The error is the title:

> CBOR tag `EpochDateTime` cannot be represented in the circe JSON AST` when using BigDecimal

**Comment by sirthias** [comment]
Ok, you don't say explicitly say so but I assume that the described error happens when you try to "cross-decode" a CBOR-encoded value (which looks like it might come from some Amazon-Service) to JSON, so you can use your existing circe decoders to deserialize it to an instance of your custom types, right?

As the _borer_ docs say, CBOR is a superset of JSON, meaning that all JSON values can be represented in CBOR but not the other way around. The error you are seeing is one such case. The CBOR encoding that you are trying to feed to your circe decoders contains a CBOR "tag", which has no corresponding counterpart in JSON.
_borer_ cannot generally know how deal with such a case and throws an error.

There are several potential work-arounds the easiest of which might be to wrap the `io.bullet.borer.compat.circe.defaultCirceJsonAstDecoder` with some simple custom logic, along these lines (untested):

```scala
implicit val myCirceJsonAstDecoder: Decoder[io.circe.Json] =
  Decoder { r =>
    io.bullet.borer.compat.circe.defaultCirceJsonAstDecoder.read {
      Integer.numberOfTrailingZeros(r.dataItem()) match {
        case io.bullet.borer.DataItem.Tag if r.hasTag(Tag.EpochDateTime) => r.skipDataItem()
        case _ => r
      }
    }
  }
```

This will simply skip all CBOR `EpochDateTime` tags before they trigger the error.
If the rest of your decoding infrastructure can still interpret everything correctly, even without these tags, you should be fine.

**Comment by etspaceman** [comment]
Thanks for the quick response! I will try this.

**Comment by etspaceman** [comment]
Getting the same. I think its due to the validation in the AstDecoder, which throws away any tag that is not `PositiveBigNum`, `NegativeBigNum` and `DecimalFraction`.

I tried to implement my own decoder which (hackily) added `r.hasTag(Tag.EpochDateTime)` to the if statement here:

https://github.com/sirthias/borer/blob/master/compat-circe/src/main/scala/io/bullet/borer/compat/circe.scala#L153

But now I have a new error:

`scala.MatchError: 2097152 (of class java.lang.Integer) (input position 63)`

**Comment by etspaceman** [comment]
I believe this is an issue with the match statement here:

https://github.com/sirthias/borer/blob/master/core/src/main/scala/io/bullet/borer/Decoder.scala#L193

**Comment by etspaceman** [comment]
@sirthias I have been having a heck of a time trying to resolve this.

So apparently the main issue that I am trying to solve is that the AWS client will encode data for timestamps differently between JSON and CBOR.

What I have attempted to do is create Encoder/Decoder instances that no longer depend on the Circe compat layer as a result. I tried to accomplish this by leveraging the `derivation` library and using `MapBasedCodecs`, while having a custom instance for `Instant` which serializes the data as the AWS client expects. However, this seems to be serializing data differently than the compatibility layer for Circe. Unfortunately the AWS SDK doesn't give me much information when it fails the request :/.

After perusing the code, my hunch is that the differences lie in the Optionality of the fields, but I'm somewhat grasping at straws here. 

Are you aware of the differences between these two approaches in terms of CBOR encoding?

**Comment by etspaceman** [comment]
I was able to implement a custom AstDecoder by implementing a custom Decoder for the EpochDateTime use case as such:

```scala
 val epochDateTimeDecoder: Decoder[Long] = Decoder { r =>
    r.dataItem() match {
      case DataItem.Long                        => r.readLong()
      case _ if r.tryReadTag(Tag.EpochDateTime) => r.readLong()
      case _                                    => r.unexpectedDataItem(expected = "Long")
    }
  }
```

My custom AstEncoder is simply a copy of the default with an added case for the tags:

```scala
else if (r.hasTag(Tag.EpochDateTime)) {
              Json.fromLong(epochDateTimeDecoder.read(r))
            }
```
