### ISSUE TITLE
Switch to sbt-bintray for publishing

### ISSUE THREAD

**Issue by sirthias** [sirthias/borer#53]
since publishing to oss.sonatype.org is increasingly becoming a major hassle due to severe upload performance issues on their oss platform.

**Comment by mushtaq** [comment]
@sirthias I hope you have come across [this thread](https://twitter.com/jvican/status/1174014550221447170) already. Suddenly people are happy with Maven Central publishing due to a feature no-one was aware of :-).

**Comment by sirthias** [comment]
Awesome!! Hadn't seen that yet. Thank you for the pointer!

**Comment by sirthias** [comment]
Bundle uploads really are a game changer!
In fact, with bundle uploads this ticket becomes obsolete, at least for now.

**Comment by plokhotnyuk** [comment]
Also, you can check if today is good day for releasing using https://status.maven.org/

**Comment by sirthias** [comment]
Thank you, @plokhotnyuk, hadn't seen that page before.
Looks useful indeed!
