### ISSUE TITLE
Java 11 really needed?

### ISSUE THREAD

**Issue by DamianReeves** [sirthias/borer#580]
I'm curious whether borer really needs to be built against Java 11, is the library actually making use of Java 11 features? Java 8 support would open things up to a larger set of users (particularly in the enterprise).

**Comment by sirthias** [comment]
Well, yes, its probably possible to have artifacts be built for Java 8.
The reason I excluded it is simply that there is no proper (i.e. fast) Java 8 JRE anymore for my current development platform (Apple Silicon). But we could certainly add a `-target 8` switch somewhere and give it a try.
I'd be happy to merge any PR...

**Comment by DamianReeves** [comment]
Sounds good.

**Comment by DamianReeves** [comment]
I don't see GitHub actions setup to build/deploy the project? What is the CI/CD process being used?

**Comment by sirthias** [comment]
Very simple.
I build and publish from my machine... :)

**Comment by DamianReeves** [comment]
Changed the JVM version and created a PR ran all tests on my machine on JVM 8.

If you are interested I can probably see about setting-up a GitHub Actions workflow (in another PR) so that you can test all PRs against both JVM 8 and 11, let me know.

**Comment by sirthias** [comment]
> If you are interested I can probably see about setting-up a GitHub Actions workflow (in another PR) so that you can test all PRs against both JVM 8 and 11, let me know.

Yes, thank you, that'd be great!
So far I couldn't be bothered w/ the setup because it was just me who added code but the GA setup has been on my list as well (although somewhere quite far back...)
