### ISSUE TITLE
DoS vulnerability of borer-compat-circe

### ISSUE THREAD

**Issue by plokhotnyuk** [sirthias/borer#584]
_Sub-quadratic_ decreasing of throughput when number of JSON object fields (with keys that have the same hash code) is increasing

On contemporary CPUs parsing of such JSON object (with a sequence of 100000 fields like below that is ~1.6Mb) can took ~60 seconds:

```
{
"!!sjyehe":null,
"!!sjyeiF":null,
"!!sjyej'":null,
"!!sjyfIe":null,
"!!sjyfJF":null,
...
}
``` 

Below are results of the benchmark where `size` is a number of such fields:

```
[info] Benchmark                        (size)   Mode  Cnt        Score   Error  Units
[info] ExtractFieldsReading.circeBorer       1  thrpt       1826943.085          ops/s
[info] ExtractFieldsReading.circeBorer      10  thrpt        284635.079          ops/s
[info] ExtractFieldsReading.circeBorer     100  thrpt         14814.658          ops/s
[info] ExtractFieldsReading.circeBorer    1000  thrpt           506.885          ops/s
[info] ExtractFieldsReading.circeBorer   10000  thrpt             3.822          ops/s
[info] ExtractFieldsReading.circeBorer  100000  thrpt             0.016          ops/s
```

To run that benchmarks on your JDK:
1. [Install latest version of `sbt`](https://www.scala-sbt.org/1.0/docs/Setup.html) and/or ensure that it already installed properly: 
```
sbt about
```

2. Clone `jsoniter-scala` repo: 
```
git clone --depth 1 https://github.com/plokhotnyuk/jsoniter-scala.git
```

3. Enter to the cloned directory and checkout for the specific branch:
```
cd jsoniter-scala
git checkout borer-compat-circe-DoS-by-hashmap-collisions
```

4. Run benchmarks:
```
sbt -no-colors 'jsoniter-scala-benchmark/jmh:run -wi 1 -i 1 ExtractFields.*circeBorer'
```

**Comment by sirthias** [comment]
Thank you, @plokhotnyuk, for this detailed report!
I'll take a look at things ASAP...
