### ISSUE TITLE
JSON representations of Float numbers contain redundant digits

### ISSUE THREAD

**Issue by plokhotnyuk** [sirthias/borer#6]
```
scala> new String(io.bullet.borer.Json.encode(1.1999999f).toByteArray)
res0: String = 1.1999999284744263
```

I would recommend to peek and adopt [the Ryu algorithm](https://github.com/ulfjack/ryu) for serialization of both `Float` and `Double` types - it is much performant and some values can be serialized using less digits than Java's `toString`.

**Comment by sirthias** [comment]
Yes, thank you for reporting!
