### ISSUE TITLE
When the encoded byte array exceeds 4m bytes, decode fails

### ISSUE THREAD

**Issue by guidoschmidt17** [sirthias/borer#610]
In a very complex scenario I noticed that with large encoded byte arrays the decoding fails. The scenario includes Lz4 compression, websocket transport and more. I removed all that.
When I encode a large object of type A into a byte array and then immediately decode it, it fails when the size of the byte array is larger than 4m. I get different errors but mostly "String or Text-Bytes but got Int (input position 4194350))"
If the size is just slightly below 4m it works as expected, but I am not sure, maybe I do something wrong.
Thanks for your support in advance.

**Comment by sirthias** [comment]
Thank you, Guido, for this report!
This looks like quite a serious problem that should be fixed.

What _borer_ and Scala version are you using?
Do you have a simple snippet of test code that demonstrates the problem and that I could use as a test for this problem?

**Comment by guidoschmidt17** [comment]
I'm using v1.10.1 (core, derivation) on Scala 3.2.2 and Scala-Js 1.12.0.
I'm trying to build a simplified reproducer, but this is far from simple as I use a lot of customized codecs and also a CodecRegistry to enable codecs on un-sealed traits. With a simple large random byte array borer works just fine. So I guess the problem is somewhere in my code. I'll provide some feedback asap.

**Comment by sirthias** [comment]
Ok, thank you!

**Comment by guidoschmidt17** [comment]
Sorry, my bad. After adding some md5 hashes to the byte arrays encoded/decoded with borer.Cbor I could see a mismatch occasionally. The corresponding Codec.bimap uses an internal buffer pool that under high load returned a wrong chunk of bytes. I was able to find and fix that while I was trying to create a reproducer. Again sorry for the noise and thx for the support.
Btw: Is this the right forum to ask questions about borer or is there some other channel like discord?

**Comment by sirthias** [comment]
No problem, Guido!
I'm glad you found the issue.
And yes, at this point it's fine to ask question right here.
As long as the volume is low there is no point in setting up anything else...

**Comment by guidoschmidt17** [comment]
Ok, thx.
