### ISSUE TITLE
Give high priority to borer (un)mashallers

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#62]
Akka-http handles (un)marshalling of a few types like `Option[T]` and `Either[A, B]` in a special way. 

Akka-http always picks up its own (un)marshallers for them ignoring `defaultBorerUnmarshaller` and `defaultBorerMarshaller` provided by borer's `akkaHttp`.

Inn our project we copy the following in the immediate lexical scope to give them a higher priority.
- `liftMarshaller` from `LowPriorityToResponseMarshallerImplicits` and
- `messageUnmarshallerFromEntityUnmarshaller` from `LowerPriorityGenericUnmarshallers`

Will it make sense to add them `akkaHttp` of the `borer-compat-akka` module?

**Comment by sirthias** [comment]
Yes, thank you, this sounds like a good idea!

**Comment by sirthias** [comment]
Let me know, @mushtaq, if the fix in https://github.com/sirthias/borer/commit/e83b7faee1d141cb2bf9ed53001fe90dfb6729de doesn't do the trick for you.

**Comment by mushtaq** [comment]
@sirthias, I managed to use AkkaHttpCompat in all the places where our custom class was being used and the code compiles, which is great!

But I am still unable to switch due to our emphasis on Json being the primary content type. I describe this requirement in a new issue: #84
