### ISSUE TITLE
Use Scala 3 syntax in documentation

### ISSUE THREAD

**Issue by hejfelix** [sirthias/borer#625]
There's a few things I would change in the documentation:

1. Explicit types for implicit values
    1. Preferably: Use Scala 3 syntax instead, e.g. `given Typeclass[T] = ...`
2. Use Scala 3 whitespace significant syntax (this is a personal preference)
3. Add some benchmarks comparing CBOR and Json sizes / performance

**Comment by sirthias** [comment]
Yes, I agree, the documentation needs to be upgraded to Scala 3.
And while we are at it, we might as well switch to the new syntax, which I too prefer over the old one in most cases.

> Add some benchmarks comparing CBOR and Json sizes / performance

Yeah, that's a nice idea.
Thank you!
