### ISSUE TITLE
Additionally expose akkaHttp companion trait 

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#63]
Latest `borer-compat-akka` exposes `object akkaHttp` which is a great addition! 

Can we also have a companion `trait akkaHttp` with the same content, but allows users to extend/mix-in and add additional (un)marshalling support as needed? 

For example, if we do not fix #62, I would like to add those two (un)marshallers in the extended `HttpCodecs` in my app.

**Comment by sirthias** [comment]
yes, ok, adding an companion trait increases flexibility even more

**Comment by sirthias** [comment]
Closed by https://github.com/sirthias/borer/commit/e83b7faee1d141cb2bf9ed53001fe90dfb6729de
