### ISSUE TITLE
Codecs for Either[A, B] should not be in the implicit scope by default

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#64]
Currently, ArrayBasedCodecs for `Either[A, B]` are in the implicit scope and picked up by default.

Given that `Either` is an ADT with both cases having a value (unlike Option), some teams may not prefer array based codec in JSON APIs.

For this purpose, we defined our own map-based codecs for Either. But every now and then we forget to bring it in the implicit scope which is detected late and leads to confusion.

We would like it if Either codecs are not in scope by default and we get a compilation error if we forget to import it explicitly (default or user-defined).

**Comment by sirthias** [comment]
Yes, I think that's a good idea.
The pre-defined `Either` codecs are indeed somewhat opinionated and certainly don't suit all or even most use cases.

We can define a handful of common `Either` encodings that can be brought into scope with a simple import and remove the default one.

**Comment by mushtaq** [comment]
For our JSON APIs, we thought keys like "Success" and "Error" make more sense.

So, we came up with (a bit roundabout) way of defining [Either codecs](https://github.com/tmtsoftware/msocket/blob/master/msocket/msocket-api/src/main/scala/msocket/api/utils/EitherCodecs.scala) via an intermediate datatype [Result](https://github.com/tmtsoftware/msocket/blob/master/msocket/msocket-api/src/main/scala/msocket/api/utils/Result.scala).

Agreed that better conventions are possible.
