### ISSUE TITLE
Add compat-pekko, as alternative to compat-akka

### ISSUE THREAD

**Issue by abrighton** [sirthias/borer#656]
We are looking into replacing akka with pekko and have a dependency on borer-compat-akka. It would be nice if you could also provide borer-compat-pekko. The code is basically the same, with "akka" replaced with "pekko".

Since our project currently depends on borer-1.7.2, I forked borer and added a branch where I made this addition:
https://github.com/tmtsoftware/borer/tree/add-pekko-to-borrer-1.7.2

I could do the same for the master branch and make a pull request if you agree. My version still depends on a local snapshot for pekko-http, but it should be released soon.

**Comment by sirthias** [comment]
Thank you, @abrighton, this is a great idea!
If you submit a PR I'll happily merge and release it...

**Comment by abrighton** [comment]
OK, done.

**Comment by sirthias** [comment]
Thank you again!
I just released _borer_ 1.11.0, which now contains the new `compat-pekko` module.
