### ISSUE TITLE
Add `borer-refined` module

### ISSUE THREAD

**Issue by sirthias** [sirthias/borer#676]
which allows for `T refined P` to be encoded using the given `Encoder[T]` and decoded using the given `Decoder[T]`, followed by the validation logic for the predicate `P`.

Implementation will probably similar to [circe-refined](https://github.com/circe/circe/blob/series/0.14.x/modules/refined/shared/src/main/scala/io/circe/refined/CirceCodecRefined.scala).

At the time of writing [refined](https://github.com/fthomas/refined) support is Scala 3 is limited.
It does work for runtime validations but for compile time verification.

**Comment by windymelt** [comment]
Hi, I'd like to tell you that [Iltotore/iron: Strong type constraints for Scala](https://github.com/Iltotore/iron) can be alternative. Despite it brings fewer default refined types than `refined`, it works well (only) for Scala 3. It has simple interface.

**Comment by windymelt** [comment]
Oops sorry there is https://iltotore.github.io/iron/docs/modules/borer.html .

**Comment by sirthias** [comment]
Thannk you, @windymelt, for reminding me about this issue.
I also prepare `iron` now over `refined` for Scala 3.
And since the current version of borer is Scala 3 only I think this ticket can be closed...
