### ISSUE TITLE
Helper to get implicit instance for Encoder/Decoder of a given type

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#77]
To fetch an implicit `Encoder` for type `T` in the current scope, currently we have to do `implicitly[Encoder[T]]`.

If `Encoder.apply` takes its parameter implicitly like below

```scala
def apply[T](implicit encoder: Encoder[T]): Encoder[T] = encoder
```

we can then just call `Encoder[T]` obtain the implicit instance.

Other alternatives are
- add another method `Encoder.of` which does the same, and rename `implicitly` method in Codec to `of`
- add another method called `Encoder.implicitly` which does the same, similar to what `Codec` has
- `Encoder.fromCodec` is related but expects full `Codec` instance to be in scope

All of the above also applies to `Decoder` too.

**Comment by sirthias** [comment]
Yes, good idea, thank you, @mushtaq!
I think I'm leaning towards simply marking the parameter of `Encoder.apply[T]` implicit, as you suggest. This would result in a way of summoning the implicit value that's identical to cats, which  is probably a good thing...

**Comment by mushtaq** [comment]
👍
