### ISSUE TITLE
Borer 1.0.0 allocates too much during encoding/decoding of small JSON messages

### ISSUE THREAD

**Issue by plokhotnyuk** [sirthias/borer#78]
Below are results for [parsing](https://github.com/plokhotnyuk/jsoniter-scala/blob/d46553aff5041472559a27f7a4b8d3dac76cf360/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/IntReading.scala) and [serialization](https://github.com/plokhotnyuk/jsoniter-scala/blob/d46553aff5041472559a27f7a4b8d3dac76cf360/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/IntWriting.scala) of a simple 10-digit number.
### 500-800 bytes per operation during parsing
![image](https://user-images.githubusercontent.com/890289/66631468-79dd0e80-ec06-11e9-8c59-07943bdf8161.png)
### 1150-1200 bytes per operation during serialization
![image](https://user-images.githubusercontent.com/890289/66631525-97aa7380-ec06-11e9-8b34-b800ce5c0065.png)

Most allocations happen during creation of `io.bullet.borer.json.DirectJsonParser` or `io.bullet.borer.output.ToByteArrayOutput$ToByteArray` instances accordingly:

![image](https://user-images.githubusercontent.com/890289/66632558-0be61680-ec09-11e9-8aa5-37816cafd2a2.png)
![image](https://user-images.githubusercontent.com/890289/66632716-5ebfce00-ec09-11e9-8539-fd985655f134.png)

W/A could be using of smaller values for `DecodingConfig.initialCharbufferSize` and `EncodingConfig.bufferSize` configuration properties for parsing and serialization of small messages. But reusing such configuration for medium and big messages introduces more overhead in run-time.

Could it be possible to use thread-local caching for them to minimize the allocation rate?

**Comment by sirthias** [comment]
Thank you for this analysis, @plokhotnyuk !
I'll look into it...
