### ISSUE TITLE
Possible denial of service when parsing a JSON number as BigInt or BigDecimal

### ISSUE THREAD

**Issue by plokhotnyuk** [sirthias/borer#8]
Currently big numbers in Java has a binary representation under hood, and parsing them from the decimal string representation has `O(n^2)` complexity.

```
scala> def timed[A](f: => A): A = { val t = System.currentTimeMillis; val r = f; println(s"Elapsed time (ms): ${System.currentTimeMillis - t}"); r }
timed: [A](f: => A)A

scala> timed(io.bullet.borer.Json.decode(("9" * 1000000).getBytes).to[BigInt].value)
Elapsed time (ms): 13151

scala> timed(io.bullet.borer.Json.decode(("9" * 1000000).getBytes).to[BigDecimal].value)
Elapsed time (ms): 13165
```

For a contemporary 1Gbit network 10ms of receiving a malicious message with a 1000000-digit number can produce 1300ms of 100% CPU load in a one core. More than 100 cores can be effectively DoS-ed at a full bandwidth rate.

Also, a lot of arithmetic operations has O(n^1.5) complexity, even such "safe" operations as `+` for a not validated scale of the input value can DoS much more efficiently by a single message with a 12-digit number:

```
scala> timed(io.bullet.borer.Json.decode(("1e-100000000").getBytes).to[BigDecimal].value)
Elapsed time (ms): 0

scala> timed(io.bullet.borer.Json.decode(("1e-100000000").getBytes).to[BigDecimal].value + 1)
Elapsed time (ms): 91591
```

So, parse them with taking in account these worst cases, especially for the systems that are opened for the wild wide world:
1) Check the length of the mantissa before parsing and the scale value after to save users from such kind of attacks.
2) For safer work at high limits you can adopt more efficient routines for parsing which has `O(n^1.5)` complexity, like [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/0702be944a72010b4ca7339e0b786e86381d928d/jsoniter-scala-core/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonReader.scala#L1477-L1589).

**Comment by sirthias** [comment]
Yup!
Thanks again!
