### ISSUE TITLE
Allow users to configure the default for Content-Type in requests and responses

### ISSUE THREAD

**Issue by mushtaq** [sirthias/borer#84]
**Current behaviour**

- Content-Type header is mandatory in requests
- Content-Type header in responses defaults to `application/cbor` if Accept header is not specified

**Requested behaviour for requests**

- Content-Type header should be optional in requests. 
- Allow the server implementor to configure the default value for Content-Type header in requests
- If a request does not have the Content-Type header, server uses the configured value as default
- If a request has the Content-Type header, server uses that value

**Requested behaviour for responses**

- Allow the server implementor to configure the default value for Content-Type header in responses
- If a request does not have the Accept header, server uses the configured value as default
- If a request has the Accept header, server uses that value

**Context**

We are using AkkaHttpCompat only for serving Json over HTTP. We use Cbor encoding a lot in other places, but do not want to make it the default for our HTTP interface. It will be great if users can configure it based on their needs.

**Comment by sirthias** [comment]
Thank you, @mushtaq, for this ticket!

> Content-Type header should be optional in requests.

I don't quite understand what you mean here.
The `Content-Type` header is not optional if the message (request or response) contains a body (entity).

Which client (layer, library) are you using?

> - Allow the server implementor to configure the default value for Content-Type header in requests
> - If a request does not have the Content-Type header, server uses the configured value as default
> - If a request has the Content-Type header, server uses that value

You mean that you'd like to inject an "artifical" `Content-Type` header if the client doesn't send one with it's request? You can do that with akka-http's routing directives, e.g. `mapRequest`.
I don't think this rather special requirement should be part of borer.

> Allow the server implementor to configure the default value for Content-Type header in responses

You can already do that.
If you extend the `AkkaHttpCompat` trait you can override the `borerFromEntityUnmarshaller` method with a call to `borerUnmarshaller(...)` that contains the configuration you require.

> - If a request does not have the Accept header, server uses the configured value as default
> - If a request has the Accept header, server uses that value

That is the content negotiation logic that akka-http already implements.
Nothing required from borer's side here.

**Comment by mushtaq** [comment]
Maybe you are right. Give me some time to articulate and reproduce the issue I am facing. I Will comment back here once I figure out where is the problem.

**Comment by mushtaq** [comment]
@sirthias I now understand how content type negotiation works. Managed to integrate the current borer behaviour in our library without much custom code. Closing this now.

**Comment by sirthias** [comment]
Great! I'm glad things worked out well concerning the integration of borer into your codebase.
